### ISSUE TITLE
Can't find “water.”

### ISSUE THREAD

**Issue by abcdvvvv** [longemen3000/ChemicalIdentifiers.jl#12]
Hello. I'm new to this pack. I tried to search for water as shown in the tutorial, but the return value is missing.
```julia
using ChemicalIdentifiers
res = search_chemical("water") # return missing
res = search_chemical((7732, 18, 5)) # return missing
```
May I ask what is going on?

**Comment by longemen3000** [comment]
hello,

Thanks for letting me know of this issue. I can reproduce it in my computer. what probably is happening is that the database file (from calebbell/chemicals) was updated, so probably i need to update some code here too

**Comment by longemen3000** [comment]
found the issue, water is now in a new database (https://github.com/CalebBell/chemicals/blob/master/chemicals/Identifiers/Inorganic%20db.tsv), it was moved last week.
You add that database yourself, or wait for a new version of this package to be released (in a few hours)

**Comment by abcdvvvv** [comment]
I see. Thank you for your reply! I will wait for the new version to be released.

**Comment by longemen3000** [comment]
The new version is already released, try it out, and if it solves your problem, feel free to close this issue.
